(define-module (core-system core-system)
  #:use-module (gnu system)
  #:use-module (gnu services)
  #:use-module (gnu services base)
  #:use-module (srfi srfi-39)
  #:use-module (core-system kernel-space kernel-space)
  #:use-module (core-system user-space root root)
  #:export (os))

(define-public os
  (operating-system
    (host-name host-name)
    (timezone system-timezone)
    (locale system-locale)
    (kernel kernel)
    (kernel-arguments kernel-arguments)
    (keyboard-layout keyboard-layout)
    (bootloader system-bootloader-configuration)
    (file-systems file-systems)
    (users users)
    (sudoers-file sudoers-file)
    (setuid-programs setuid-programs)
    (firmware kernel-system-packages)
    (packages root-system-packages)
    (services (append kernel-system-services root-system-services))))
