cursor #e4e2e3
cursor_text_color #c8c6c7

foreground            #e4e2e3
background            #131315
selection_foreground  #2b303c
selection_background  #c4c6d0
url_color             #ffffff

color0   #2a2a2a
color1   #8c0c0b
color2   #0a7209
color3   #7f7511
color4   #223b74
color5   #0f1932
color6   #2b303c
color7   #1a1a1a
color8   #2e2e2e
color9   #a52120
color10  #148c13
color11  #998e21
color12  #313848
color13  #215084
color14  #3d2e84
color15  #1a1a1a
