---
themes:
  white:
    bg: "#FFFFFF"
    fg: "#8B0000"
    current_bg: "#FFFFFF"
    current_fg: "#8B0000"
    saved_bg: "#FFFFFF"
    saved_fg: "#8B0000"
    palette:
      black: "#FFFFFF"
      red: "#8B0000"
      green: "#8B0000"
      yellow: "#8B0000"
      blue: "#A52A2A"
      magenta: "#8B0000"
      cyan: "#A52A2A"
      white: "#8B0000"
      bright_black: "#FFFFFF"
      bright_red: "#A52A2A"
      bright_green: "#A52A2A"
      bright_yellow: "#A52A2A"
      bright_blue: "#8B0000"
      bright_magenta: "#A52A2A"
      bright_cyan: "#A52A2A"
      bright_white: "#8B0000"
