(defun dashboard-open ()
  "Open dashboard."
  (interactive)
  (let ((buf (get-buffer-create "*Dashboard*")))
    (with-current-buffer buf
      (erase-buffer)
      (insert "╔════════════════════════════════════════════╗\n")
      (insert "║         LITERATIVEOS DASHBOARD             ║\n")
      (insert "╚════════════════════════════════════════════╝\n\n")
      (insert "📊 SYSTEM\n")
      (insert "  Uptime:    " (string-trim (shell-command-to-string "uptime -p")) "\n")
      (insert "  Memory:    " (car (split-string (string-trim (shell-command-to-string "free -h | grep Mem")) "\\s+") 2) "\n")
      (insert "  Disk:      " (nth 4 (split-string (string-trim (shell-command-to-string "df -h / | tail -1")) "\\s+")) "\n\n")
      (insert "⚙️  EMACS\n")
      (insert "  Packages:  " (number-to-string (length (list (featurep 'avy) (featurep 'god-mode) (featurep 'opencode) (featurep 'org-mcp)))) " loaded\n")
      (insert "  Configs:   ~/.config/emacs/Literative Configurations/ ✓\n\n")
      (insert "🤖 OPENCODE\n")
      (insert "  Status:    " (if (featurep 'opencode) "✓ Ready" "✗ Not loaded") "\n")
      (insert "  org-mcp:   " (if (featurep 'org-mcp) "✓ Ready" "✗ Not loaded") "\n\n")
      (insert "📁 QUICK ACTIONS\n")
      (insert "  M-x magit-status       - Git\n")
      (insert "  M-x opencode-new-session - OpenCode\n")
      (insert "  M-x org-mcp-enable     - MCP Server\n")
      (insert "  M-x find-file          - Files\n\n")
      (insert "Press q to close")
      (read-only-mode 1)
      (local-set-key "q" 'quit-window))
    (switch-to-buffer buf)))

(provide 'dashboard)
