;;; OpenCode AI coding assistant
(define-public opencode
  (package
    (name "opencode")
    (version "1.2.26")
    (synopsis "AI-powered coding assistant")
    (description "OpenCode is an AI-powered coding assistant that helps with software development tasks")
    (home-page "https://opencode.ai")
    (license asl2.0)
    (source
     (origin
       (method url-fetch)
       (uri "https://github.com/anomalyco/opencode/releases/download/v1.2.26/opencode-linux-x64.tar.gz")
        (sha256 (base32 "0m140rr127s9j44ng6z2h6b3vgvg2xqz7qp0c2df7qs6vk8nsyiw"))))
    (build-system trivial-build-system)
    (native-inputs (list coreutils tar gzip patchelf glibc bash))
    (arguments
     '(#:builder
       (let* ((out (assoc-ref %outputs "out"))
              (src (assoc-ref %build-inputs "source"))
              (coreutils (assoc-ref %build-inputs "coreutils"))
              (tar (assoc-ref %build-inputs "tar"))
              (gzip (assoc-ref %build-inputs "gzip"))
              (patchelf (assoc-ref %build-inputs "patchelf"))
              (glibc (assoc-ref %build-inputs "glibc"))
              (bash (assoc-ref %build-inputs "bash"))
              (tarbin (string-append tar "/bin/tar"))
              (mvbin (string-append coreutils "/bin/mv"))
              (cpbin (string-append coreutils "/bin/cp"))
              (chmodbin (string-append coreutils "/bin/chmod"))
              (mkdirbin (string-append coreutils "/bin/mkdir"))
              (patchelf-bin (string-append patchelf "/bin/patchelf"))
              (ld-linux (string-append glibc "/lib/ld-linux-x86-64.so.2")))
           (setenv "PATH" (string-append coreutils "/bin:" tar "/bin:" gzip "/bin"))
           (system (string-append mkdirbin " -p " out "/bin " out "/share/opencode"))
           (system (string-append tarbin " -xzf " src " -C " out "/share/opencode"))
           (system (string-append chmodbin " a+x " out "/share/opencode/opencode"))
           (system (string-append patchelf-bin " --set-interpreter " ld-linux " " out "/share/opencode/opencode"))
           (with-output-to-file (string-append out "/bin/opencode")
             (lambda ()
               (display (string-append "#! " bash "/bin/bash\n"))
               (display "export OPENCODE_EXPERIMENTAL_MARKDOWN=0\n")
               (display (string-append "exec " out "/share/opencode/opencode \"$@\"\n"))))
           (system (string-append chmodbin " a+x " out "/bin/opencode")))))))
