#+title:      Most Habits are Good
#+date:       [2024-12-20 Fri 08:42]
#+filetags:   :workflow:
#+identifier: 20241220T084242


* Most habits are good.
  - They are working for you, you just don't realize it.
  - There are parts of our brain that we really don't understand how they work. We don't have access to them. I've called these the 'Second-self.' It's another self that we don't interact with very much. We just see the effects of our habits, but we don't necessarily control them.
  - Because we don't have access to it, we are very much influenced by the things we can know. And the 'Introspection Illusion' is our tendency to focus too much on the pieces that we know, the experiences we have; our feelings, our beliefs, the reasons why we do things. So you don't recognize that a lot of the things that you do are out of habit instead of out of choice.
- It's hard to imagine that people back in the 1990s did not know that they were supposed to eat more fruits and vegetables than they are, but they didn't. The 5 A Day Program was extremely successful. In one way, it convinced us all to eat more fruits and vegetables. So it was really effective at informing people, getting them to realize they should change their behavior. They were just trying to convince people, thinking, "If we can only get people to realize they need to do this, they will of course do it because it's good for your health." People don't work that way. The campaign did not change people's habits. It changed their understanding. So the habit is a default. It's what you do when you're not thinking, and you intervene on that with more conscious, thoughtful decisions.
- Again, you have this 'habit self' out here, eating things that we've all eaten all along before the campaign. And then, our 'decision-making self' feeling guilty because we're not following through with what we now know we should do. The habit system is not part of our conscious awareness; it's part of the unconscious. So if you have these two systems, the question is, 'How do they relate to each other?' Unless we have some understanding of how that works, it sets us up to be fighting ourselves. So we have habits to do one thing that we don't really recognize, and then we have our conscious thoughts and feelings on the other hand. And in order to really meet your goals effectively, those two things have to be more integrated. If you are a successful person, your habits and your more conscious, 'thoughtful self' are definitely working together.
- What we've learned in the past couple of years is that people who have really good self-control are actually acting on habit. They had figured out how to form habits that met their goals- for health, for productivity, for relationships. Having an effective habit can set you up to do the things that you want in life, and can integrate both your habit self and your more thoughtful, conscious self.

