[theme]
name = "red"

[colors]
Base = "#8B0000"
Guidance = "#8B0000"
Annotation = "#8B0000"
AlertInfo = "#8B0000"
AlertWarn = "#8B0000"
Title = "#8B0000"
Muted = "#8B0000"
Important = "#8B0000"
AlertError = "purple"