# Lock-screen greeter Hyprland config
exec-once = LOCK-SCREEN_MODE=greetd quickshell --path /home/aoeu/.config/lock-screen/greeter.qml

animations {
    enabled = false
}

misc {
    background_color = rgba(0E0E0EFF)
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
