;;; GitHub CLI - GitHub command line tool
(define-module (tools gh)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system trivial)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages base)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages elf))

(define-public gh
  (package
    (name "gh")
    (version "2.63.0")
    (synopsis "GitHub CLI tool")
    (description "gh is GitHub CLI tool for GitHub")
    (home-page "https://cli.github.com")
    (license license:expat)
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://github.com/cli/cli/releases/download/v" version "/gh_" version "_linux_amd64.tar.gz"))
       (sha256 (base32 "1yymhcng5vdwcv241injwhjwm2hsvai662q0z6n82gk9ci8xza53"))))
    (build-system trivial-build-system)
    (native-inputs (list coreutils tar gzip patchelf glibc))
    (arguments
     '(#:builder
       (let* ((out (assoc-ref %outputs "out"))
              (src (assoc-ref %build-inputs "source"))
              (coreutils (assoc-ref %build-inputs "coreutils"))
              (tar (assoc-ref %build-inputs "tar"))
              (gzip (assoc-ref %build-inputs "gzip"))
              (patchelf (assoc-ref %build-inputs "patchelf"))
              (glibc (assoc-ref %build-inputs "glibc"))
              (tarbin (string-append tar "/bin/tar"))
              (mvbin (string-append coreutils "/bin/mv"))
              (chmodbin (string-append coreutils "/bin/chmod"))
              (mkdirbin (string-append coreutils "/bin/mkdir"))
              (patchelf-bin (string-append patchelf "/bin/patchelf"))
              (ld-linux (string-append glibc "/lib/ld-linux-x86-64.so.2")))
          (setenv "PATH" (string-append coreutils "/bin:" tar "/bin:" gzip "/bin"))
          (system (string-append mkdirbin " -p " out))
          (system (string-append tarbin " -xzf " src " -C " out))
          (system (string-append chmodbin " a+x " out "/bin/gh"))
          (system (string-append mkdirbin " -p " out "/bin"))
          (system (string-append mvbin " " out "/gh_2.63.0_linux_amd64/bin/gh " out "/bin/gh"))
          (system (string-append patchelf-bin " --set-interpreter " ld-linux " " out "/bin/gh")))))))
