#+title:      Gnu Zile
#+date:       [2025-01-02 Thu 18:54]
#+filetags:   :emacs:
#+identifier: 20250102T185409

GNU Zile is a lightweight Emacs clone. Zile is short for Zile Is Lossy Emacs. Zile has been written to be as similar as possible to Emacs; every Emacs user should feel at home.

Zile has all of Emacs's basic editing features: it is 8-bit clean (though it lacks Unicode support), and the number of editing buffers and windows is only limited by available memory and screen space respectively. Registers, minibuffer completion and auto fill are available. Function and variable names are identical with Emacs's.

However, all of this is packed into a program which typically compiles to about 130Kb.

Documentation
Zile is self-documenting: it has built-in help on its features. It also comes with a brief man page, obtained by running man zile, and a FAQ, which can be found along with a few other files in /usr/share/doc/zile/, /usr/local/share/doc/zile/, or similar directories on your system.

