
#################
### AUTOSTART ###
#################
# Lock screen immediately on start

 exec-once = hyprpaper
 exec-once = wezterm
 exec-once = hyprsunset
 exec-once = hypridle
 exec-once = nyxt
 exec-once = pypr
 exec-once = /usr/local/bin/pypr --debug /tmp/pypr.log
# exec-once = ~/.config/hypr/scripts/wallpaper-picker.sh

