exec-once = $terminal
exec-once = qutebrowser
exec-once = hypridle
exec-once = swww-daemon
exec-once = pypr
exec-once = LOCK-SCREEN_MODE=lockd quickshell --path /home/aoeu/.config/lock-screen/greeter.qml