general {
    gaps_in  = 2
    gaps_out = 2
    border_size = 1

    col.active_border   = rgba(8B0000ff) rgba(DC143Cff) rgba(A52A2Aff) 45deg
    col.inactive_border = rgba(2a0000aa)

    resize_on_border = false
    allow_tearing    = true
    layout           = monocle
}