general {
    gaps_in = 2
    gaps_out = 2
    border_size = 1

    col.active_border = rgba(8B0000ee) rgba(A52A2Aee) 45deg
    col.inactive_border = rgba(8B0000aa)

    resize_on_border = false
    allow_tearing = false

    layout = scrolling
}