$mainMod = SUPER
$terminal = wezterm
$editor   = emacs
$browser  = nyxt
$launcher = wofi

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, K, killactive
bind = $mainMod, D, exec, $launcher
bind = $mainMod, E, exec, $editor
bind = $mainMod, B, exec, $browser
bind = $mainMod, W, hyprexpo:expo, toggle
bind = $mainMod, F, fullscreen
bind = $mainMod, Space, easymotion, action:hyprctl dispatch focuswindow address:{}
bind = $mainMod, R, exec, hyprctl reload
bind = $mainMod, Q, exec, hyprctl dispatch exit

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

