# Configure your monitors here if needed

# Execute the lock-screen greeter in greetd mode
exec-once = LOCK-SCREEN_MODE=greetd quickshell --path /opt/lock-screen/greeter.qml

animations {
    # Remove launch transitions (hyprland zoom effect)
    enabled = false
}

misc {
    # Hides the hyprland background
    background_color = rgba(0E0E0EFF)
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
