#+title:      Core Values
#+date:       [2024-12-20 Fri 15:40]
#+filetags:   :mindset:
#+identifier: 20241220T154022


* Core values

  Because this time we're looking at Disciplines. If you've been raised in a, let's be polite about this, developing family, the word discipline could have physical connotations. But that's not what this is about. Discipline means order and the ability to organize specific elements in your life with strategic long-term purpose. Discipline allows you to build yourself sustainably. It's what those who do not desire to leave their lives up to chance will always use as a better option. With that said, here are 15 disciplines you should have in life.

1. Discipline Your Thoughts

   We've learned that everything we do begins with a neural spark inside the brain. Your thoughts quite literally dictate your future. Did you ever take the time to monitor what's going on in your mind during the day? You'll be shocked by the things you'll find yourself thinking about and how much buzz is there in the first place. You have the power to discipline your mind through practice and focus it on the important things you need to solve. Your mind is a gold mine, only the gold is buried under all that noise.

2. Discipline Your Mornings

   We've learned that people who discipline their mornings almost get an extra day's worth of work in. You have the power to jumpstart your day. As with everything on this list, small actions compound over extended periods of time. If you get one small thing done every morning in a year, you would have achieved 360 things, more than everyone else, assuming you work the same as them the rest of the day. That's the power of disciplining your mornings.

3. Discipline Your Friendships

   We've learned that the quality of your life is determined by the quality of the friendships you establish along the way. What if we told you your life would almost be the same as the ones of your friends? 10 to 15 variation, would you be happy? We're all social creatures, and our social environment is the foundation of building our future life. Hang out with losers, and you will be a loser yourself. Your life is tied to your friends like a boat is tied to other boats. If all these boats are going one way and you're going another, they will drag you in the direction they're heading. We love to think that our boat will manage to paddle faster and bring everyone with us, but that's not always what happens.

4. Discipline Your Environment

   We are a byproduct of the environment we grow in. Few people understand that they can choose to change their environment, and it's quite easy to do. Even more so, a change in environment has immediate impacts on the way you experience life. Your environment is one of the deepest ingredients of who you are, so make sure you find a good one.

5. Discipline Your Goals

   We've learned that we become what we are willing to go after. Yet, most people settle for what is convenient. Too many people settle for too little, not because they wouldn't want more, but because they don't know how to get more. The main reason why most successful people achieve success is because they make it their goal to get there. Success is a byproduct of hitting your personal goals.

6. Discipline What You Consume

   We've learned that who we are runs on the fuel we put into ourselves. The better your inputs, the better your outputs. You want to be treated as an adult? You better start making decisions like an adult. Entertainment and dessert have their place in life too, but so many people only consume the dessert in its many forms of consumption. The brutal truth they eventually find out is that dessert doesn't get you the gains you are shooting for.

7. Discipline Your Desires

   We've learned that desire is a contract you make with yourself to not be happy until the desire is fulfilled. One should pick their desires very carefully, for desires are very strong. If you want to be successful in life, pick very few desires and go after them with all you've got. Your end goal is to be desire-free, to have everything you need and not feel like you need anything else.

8. Discipline Your Addictions

   We've learned that addictions are a trade you make with the world, where in exchange for temporary pleasure, you give them a part of you. Addiction in any form is detrimental to your well-being. Identify it in its beginning stages and find ways to remove the cancer from your life, even if that requires professional help.

9. Discipline Your Body

   We've learned that the average person has thousands of desires, a sick person only has one. Your body weight limits your ability to live certain experiences. Let the pandemic be your wake-up call to get yourself a strong body.

10. Discipline Your Progress and Growth

    We've learned that the feeling of being alive comes from growth. Most people believe that their education ends with school, yet everyone agrees schools no longer educate you for the real world. Coming back every Sunday builds and reinforces those building blocks on which your life stands.

11. Discipline the Way People Perceive You

    We've learned that we are what other people think we are. One should discipline the way they present themselves to the world, for that is the only way the world will remember who you are.

12. Discipline Your Impact

    We've learned that the value of an individual is determined by what they leave behind when they're alive. Discipline yourself to have an impact, the scale you have right now.

13. Discipline Your Inner Happiness

    We've learned that being happy or not is a choice we have to make every day. The most valuable thing we found is that happiness does not depend on other facts.

14. Discipline Your Sleep

    We'd rather spend time with people who've had eight hours of sleep than people who only slept for four hours. Sleep is crucial for both immediate goals and creative leaps.

15. Discipline Yourself

    Nobody cares enough about you to make you the priority, so you have to make yourself a priority. Competing with yourself is the ultimate positive sum game.

**Special Bonus: Discipline Your Ego**

    Many times in life, you'll feel the need to act on ego. Ego is false confidence. Allow yourself the luxury for them to be impressed by your progress, not the effort you're making just to impress them.
  
